name: example-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - scikit-learn
  - matplotlib
  - opencv
  - nltk      
  - tweepy        
  - seaborn     
  - pandas    
  - numpy 
  - wordcloud
  - stylecloud
